# Generated by Django 4.2 on 2024-07-01 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="created_at",
            new_name="payment_date",
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="payment_type",
            new_name="payment_method",
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="status",
            new_name="payment_status",
        ),
    ]
